os: osx
osx_image: xcode12.2

language: node_js
node_js:
  - "14"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm install -g electron-packager

install:
  - npm install

script:
  - npm run build

after_success:
  - electron-packager . MyApp --platform=darwin --arch=x64 --out=dist --overwrite

notifications:
  email: false
