version: 2.1

jobs:
  build:
    machine:
      image: circleci/macos:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build Electron app
          command: npm run build

      - store_artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - build
